### ISSUE TITLE
Change to the scope section not mentioned in the change sections

### ISSUE THREAD

**Issue by frivoal** [w3c/charter-html#142]
One paragraph was dropped form the scope section. This is in the current charter, but not in the proposed one:

> The Web Platform Working Group should develop modular specifications to the greatest extent possible for the development of the HTML language, allowing extension specifications to define new elements, new attributes, new values for attributes that accept defined sets of keywords, and new APIs.

[See Diff](http://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2016%2F11%2Fwebplatform-charter.html&doc2=http%3A%2F%2Fw3c.github.io%2Fcharter-html%2Fwebplat-wg.html)

If that is an accident, it should be restored. If that is not an accident, this change should be listed in the ["Changes from the previous charter" section](http://w3c.github.io/charter-html/webplat-wg.html#changes-from-wp1), with a rationale for the change.

**Comment by chaals** [comment]
Yeah it was deliberate - since we discuss this in specific instances but there seems not to be a clear one-size-fits-all answer in practice. Sometimes tiny things are in extensions, sometimes it makes more sense to fold in largish chunks.

I think the preference is for modularity, but we recognise that's harder to achieve than just liking it, and the tradeoffs in each case are different.

I'll add it to the change log.
