### ISSUE TITLE
WebPlat charter: Confirming consensus

### ISSUE THREAD

**Issue by LJWatson** [w3c/charter-html#152]
Feedback from the AC review:
The charter states that consensus on decisions taken on calls or at meetings is provisional until confirmed online, when the decision is shared via the meeting minutes. This is insufficient because meeting minutes are easily missed. A clear message with an appropriate title ("CFC for XYZ" for example) should be required.

**Comment by LJWatson** [comment]
We already post CFCs on Github, with a "Notice of CFC" email sent to the relevant email list. Recognising this practice in the charter seems like a good idea to me.

**Comment by chaals** [comment]
We currently also allow decisions to be taken and advised through the minutes - should the text

>Any resolution taken in a face-to-face meeting or teleconference is to be considered provisional until 10 (ten) working days after the publication of the resolutions in meeting minutes sent to the appropriate working group mailing list

be changed to state that "decisions" taken in synchronous meetings must be confirmed by a CfC?

There is a tension with the "edit-first, seek forgiveness" work mode, and with the sense that people don't want to re-hash old discussions because someone didn't notice them at the time - but that poor decisions should of course be revisited.

I suggest that any change we make clarify that by "decision" we mean "Working Group decision to resolve an issue", not just ordinary proposed changes to specs, which can be revisited. Suggested text or a PR would be helpful.

**Comment by LJWatson** [comment]
I think the intention of this feedback is to prevent resolutions made at meetings going by unnoticed by the rest of the WG because they're buried somewhere inside (often lengthy) minutes. I don't get the impression the intention is to turn every editorial decision into a production.

**Comment by LJWatson** [comment]
We could revise the work mode document to clarify this, but doing it in the charter seems like a worthwhile exercise.

I propose we change this:
>"Any resolution taken in a face-to-face meeting or teleconference is to be considered provisional until 10 (ten) working days after the publication of the resolutions in meeting minutes sent to the appropriate working group mailing list as described in the work mode documents. If no objections are raised on the mailing list within that time, the resolution will be considered to have consensus as a resolution of the Working Group.">

To:
>"Any resolution taken in a face-to-face meeting or teleconference is to be considered provisional until 10 (ten) working days after the publication of the resolutions in meeting minutes. When the meeting minutes are sent to the appropriate working group mailing list as described in the work mode document, the presence of formal resolutions will be clearly indicated in the email. If no objections are raised on the mailing list within that time, the resolution will be considered to have consensus as a resolution of the Working Group."
