### ISSUE TITLE
define roles for the entire set of stakeholders

### ISSUE THREAD

**Issue by rubys** [w3c/charter-html#19]
The Charter HTML plan specifically calls out "(true) invited experts" and "those with authority over what gets committed to a consumer browser engine codebase".  

The W3C process is targeted at the "entire set of stakeholders of the Web community".

Please spell out the role for everybody, including the criteria for (true) invited experts, and the role that they play.

**Comment by cwilso** [comment]
I would explicitly point out those two different groups are mentioned in WILDLY different contexts.  The implication from this issue is that the charter plan identifies browser engine committers as specially blessed in the process, which is not true.

**Comment by plehegar** [comment]
@rubys, a (true) invited experts is "an individual with a particular expertise", per
  http://www.w3.org/2014/Process-20140801/#invited-expert-wg
By far, not all invited experts in the HTML working group match this description. Now, that doesn't mean we would exclude the public for contributing. That's not what's happening in the CSS Working Group for example.
I agree with @cwilso that the other mention is mixing two different topics. In fact, I'm proposing to drop the mention of browser meeting from the plan because its impact is more than the scope of the plan anyway.
