### ISSUE TITLE
Test reports don't have to be perfect

### ISSUE THREAD

**Issue by plehegar** [w3c/charter-html#32]
The charter should say something about test reports, ie we don't need to have 100% passes on the test report in order to move to Recommendation. Folks assume too often otherwise at the moment. It's actually fairly common to not have 2 passes on all tests nowadays.

**Comment by adrianba** [comment]
Agreed. In the past there have been specs that didn't move forward because there weren't two passing implementations for every single test in the test suite.

At a certain point where there is:
1. Consensus in the group that the spec is complete, implementable, and broadly interoperable
2. Good evidence of cross-browser use of the features in the spec on the web
3. A test suite that provides evidence to support the position that there is good (though perhaps not perfect) interop
4. Consensus that any places where the test suite shows differences in implementations have little impact on usage on the web and that the spec still describes what the group aspires to see implementations actually do (and of course believes is still compatible with the web).

...then the spec should move forward to PR. There is still an opportunity to object at this point.

If we were confident that getting to Recommendation only happened when all bugs were fixed then this could be viewed as less of a problem. Unfortunately we still find issues including interop or web compatibility issues after Rec so we will still need to go back and fix things later. Getting to Rec earlier locks in IPR commitments and if we end up having to do a few more bug fixes later then so be it. Better that than have a spec languish in CR for months or years with no IPR commitment in the hope that someone does the work to push it over the finish line.

**Comment by wayneca** [comment]
That may also help with the level of interest in html5 maintenance.  if there were more frequent publications of fixes in updated RECs, there would be more reason to pay attention to it.  Otherwise, there's no urgency to pay attention because it isn't changing the REC any time soon and you can put it off until later.  For substantive corrections that aren't new features, it would just be restarting at CR, so could have an updated REC 60 days later.  If that was happening regularly, it may attract interest in working on the spec after REC.

Testing could also be just for the most important areas, not for features that are already in broad use.  The world is testing the drafts that are being implemented.  Tests could focus on important features where incompatibility may not be noticed as the drafts are implemented and used.  Even after REC, tests could be added -- but that shouldn't hold up REC when things are implemented and successfully being used (and where the REC can be fixed in a fairly short time)

**Comment by wayneca** [comment]
There is text in the proposed WebApps Charter where it looks like the test suites have to cover the entire spec or that the entire deliverable has to be implemented, rather than each feature.  Here are the places that may need to be changed:

From the WG Charter:   "Test suites for each deliverable with conformance criteria."

From the WG Charter:  "A comprehensive test suite for all features of a specification is necessary to ensure the specification's robustness"

Should it be clear the test suites don't have to test every feature, that they could be restricted to features where there are particular needs to check for compatibility.

From the WG Charter:  "Availability of multiple, independent, interoperable browser implementations of each deliverable "

Each "deliverable" or is it "each feature in each deliverable"?  No browser has to implement the whole deliverable.
